# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.8'

services:
  bestpracticedockerapi:
    image: bestpracticedockerapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001:5000
